
version: 0.2

phases:
  build:
    commands:
       - ls -alhrt
       - echo "danish"
       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
       - echo "export CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION" > envs
       - cat envs
       - . ./envs
       - . ./env2
